[package]
name = "sandcastle-vulkano"
version = "0.0.1"
authors = ["Tom Burdick <thomas.burdick@gmail.com>"]

[dependencies]
vulkano = "0.9"
vulkano-shaders = "0.9"
sandcastle = { path = "../sandcastle" }
